// Dashboard constants for gym management application

export const DASHBOARD_STATS = {
  admin: [
    {
      id: 'totalMembers',
      title: 'Total Members',
      value: 1247,
      change: '+12%',
      changeType: 'positive',
      icon: 'People',
      color: 'primary',
    },
    {
      id: 'activeTrainers',
      title: 'Active Trainers',
      value: 18,
      change: '+2',
      changeType: 'positive',
      icon: 'FitnessCenter',
      color: 'warning',
    },
    {
      id: 'monthlyRevenue',
      title: 'Monthly Revenue',
      value: '$45,320',
      change: '+8.5%',
      changeType: 'positive',
      icon: 'AttachMoney',
      color: 'success',
    },
    {
      id: 'equipmentStatus',
      title: 'Equipment Issues',
      value: 3,
      change: '-2',
      changeType: 'positive',
      icon: 'Build',
      color: 'error',
    },
  ],
  trainer: [
    {
      id: 'myMembers',
      title: 'My Members',
      value: 45,
      change: '+3',
      changeType: 'positive',
      icon: 'People',
      color: 'primary',
    },
    {
      id: 'todayClasses',
      title: "Today's Classes",
      value: 6,
      change: '2 upcoming',
      changeType: 'info',
      icon: 'Schedule',
      color: 'warning',
    },
    {
      id: 'weeklyHours',
      title: 'Weekly Hours',
      value: 32,
      change: '+4h',
      changeType: 'positive',
      icon: 'Timer',
      color: 'success',
    },
    {
      id: 'memberProgress',
      title: 'Member Progress',
      value: '87%',
      change: '+5%',
      changeType: 'positive',
      icon: 'TrendingUp',
      color: 'info',
    },
  ],
  member: [
    {
      id: 'workoutsThisMonth',
      title: 'Workouts This Month',
      value: 16,
      change: '+4',
      changeType: 'positive',
      icon: 'FitnessCenter',
      color: 'primary',
    },
    {
      id: 'caloriesBurned',
      title: 'Calories Burned',
      value: '8,240',
      change: '+320',
      changeType: 'positive',
      icon: 'LocalFireDepartment',
      color: 'error',
    },
    {
      id: 'membershipDays',
      title: 'Membership Days Left',
      value: 47,
      change: 'Expires soon',
      changeType: 'warning',
      icon: 'CardMembership',
      color: 'warning',
    },
    {
      id: 'nextClass',
      title: 'Next Class',
      value: 'HIIT',
      change: 'Today 6:00 PM',
      changeType: 'info',
      icon: 'Schedule',
      color: 'success',
    },
  ],
};

export const CHART_DATA = {
  membershipGrowth: {
    data: [
      { month: 'Jan', members: 980, newMembers: 45 },
      { month: 'Feb', members: 1020, newMembers: 52 },
      { month: 'Mar', members: 1095, newMembers: 89 },
      { month: 'Apr', members: 1156, newMembers: 67 },
      { month: 'May', members: 1203, newMembers: 58 },
      { month: 'Jun', members: 1247, newMembers: 71 },
    ],
  },
  revenueByMonth: {
    data: [38500, 42000, 39800, 44200, 47300, 45320],
    labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
  },
  classAttendance: {
    data: [
      { class: 'HIIT', attendance: 85 },
      { class: 'Yoga', attendance: 92 },
      { class: 'CrossFit', attendance: 78 },
      { class: 'Pilates', attendance: 88 },
      { class: 'Spinning', attendance: 95 },
    ],
  },
  memberWorkouts: {
    data: [
      { day: 'Mon', workouts: 4 },
      { day: 'Tue', workouts: 6 },
      { day: 'Wed', workouts: 3 },
      { day: 'Thu', workouts: 5 },
      { day: 'Fri', workouts: 7 },
      { day: 'Sat', workouts: 8 },
      { day: 'Sun', workouts: 2 },
    ],
  },
  trainerSchedule: {
    data: [
      { time: '6:00', classes: 2 },
      { time: '8:00', classes: 3 },
      { time: '10:00', classes: 4 },
      { time: '12:00', classes: 2 },
      { time: '14:00', classes: 3 },
      { time: '16:00', classes: 5 },
      { time: '18:00', classes: 6 },
      { time: '20:00', classes: 4 },
    ],
  },
};

export const RECENT_ACTIVITIES = {
  admin: [
    {
      id: 1,
      type: 'member',
      message: 'New member Sarah Johnson joined',
      time: '2 hours ago',
      avatar: 'SJ',
      color: 'primary',
    },
    {
      id: 2,
      type: 'payment',
      message: 'Monthly payment received from John Doe',
      time: '4 hours ago',
      avatar: 'JD',
      color: 'success',
    },
    {
      id: 3,
      type: 'equipment',
      message: 'Treadmill #3 maintenance completed',
      time: '1 day ago',
      avatar: 'T3',
      color: 'warning',
    },
    {
      id: 4,
      type: 'trainer',
      message: 'New trainer Mike Wilson onboarded',
      time: '2 days ago',
      avatar: 'MW',
      color: 'info',
    },
  ],
  trainer: [
    {
      id: 1,
      type: 'class',
      message: 'HIIT class completed - 12 attendees',
      time: '1 hour ago',
      avatar: 'H',
      color: 'success',
    },
    {
      id: 2,
      type: 'member',
      message: 'New member assigned: Emma Davis',
      time: '3 hours ago',
      avatar: 'ED',
      color: 'primary',
    },
    {
      id: 3,
      type: 'progress',
      message: 'Tom Smith achieved weight loss goal',
      time: '1 day ago',
      avatar: 'TS',
      color: 'success',
    },
    {
      id: 4,
      type: 'schedule',
      message: 'Yoga class rescheduled for tomorrow',
      time: '2 days ago',
      avatar: 'Y',
      color: 'warning',
    },
  ],
  member: [
    {
      id: 1,
      type: 'workout',
      message: 'Completed 45-min cardio session',
      time: '3 hours ago',
      avatar: 'C',
      color: 'success',
    },
    {
      id: 2,
      type: 'class',
      message: 'Booked HIIT class for tomorrow',
      time: '1 day ago',
      avatar: 'H',
      color: 'primary',
    },
    {
      id: 3,
      type: 'achievement',
      message: 'Reached 10 workout milestone!',
      time: '2 days ago',
      avatar: '🏆',
      color: 'warning',
    },
    {
      id: 4,
      type: 'measurement',
      message: 'Updated body measurements',
      time: '3 days ago',
      avatar: 'M',
      color: 'info',
    },
  ],
};

export const QUICK_ACTIONS = {
  admin: [
    { label: 'Add New Member', icon: 'PersonAdd', path: '/members/add' },
    { label: 'View Reports', icon: 'Assessment', path: '/reports' },
    { label: 'Manage Equipment', icon: 'Build', path: '/equipment' },
    { label: 'Financial Overview', icon: 'AttachMoney', path: '/finance' },
  ],
  trainer: [
    { label: 'Schedule Class', icon: 'Event', path: '/classes/schedule' },
    { label: 'View My Members', icon: 'People', path: '/my-members' },
    { label: 'Member Progress', icon: 'TrendingUp', path: '/progress' },
    { label: 'Equipment Check', icon: 'FitnessCenter', path: '/equipment' },
  ],
  member: [
    { label: 'Book a Class', icon: 'Event', path: '/classes' },
    { label: 'Track Workout', icon: 'FitnessCenter', path: '/workouts' },
    { label: 'View Progress', icon: 'TrendingUp', path: '/progress' },
    { label: 'Update Profile', icon: 'Person', path: '/profile' },
  ],
};
