// Membership & Package Management Constants

export const MEMBERSHIP_TYPES = {
  basic: 'Basic',
  premium: 'Premium',
  vip: 'VIP',
  student: 'Student',
  corporate: 'Corporate',
  family: 'Family',
};

export const MEMBERSHIP_DURATIONS = {
  monthly: 'Monthly',
  quarterly: 'Quarterly',
  semiannual: 'Semi-Annual',
  annual: 'Annual',
  lifetime: 'Lifetime',
};

export const SUBSCRIPTION_STATUS = {
  active: 'Active',
  expired: 'Expired',
  suspended: 'Suspended',
  cancelled: 'Cancelled',
  pending: 'Pending',
};

export const PAYMENT_STATUS = {
  paid: 'Paid',
  pending: 'Pending',
  overdue: 'Overdue',
  failed: 'Failed',
};

export const PACKAGE_STATUS = {
  active: 'Active',
  inactive: 'Inactive',
  archived: 'Archived',
};

// Mock Membership Packages
export const MOCK_MEMBERSHIP_PACKAGES = [
  {
    id: 'PKG001',
    name: 'Basic Monthly',
    type: 'basic',
    duration: 'monthly',
    price: 49.99,
    description: 'Access to gym equipment and basic facilities',
    features: [
      'Gym equipment access',
      'Locker room access',
      'Basic fitness assessment',
      'Mobile app access',
    ],
    status: 'active',
    maxMembers: null,
    createdDate: '2024-01-01',
    lastModified: '2024-01-15',
  },
  {
    id: 'PKG002',
    name: 'Premium Monthly',
    type: 'premium',
    duration: 'monthly',
    price: 79.99,
    description:
      'Enhanced membership with group classes and personal training sessions',
    features: [
      'All Basic features',
      'Group fitness classes',
      '2 personal training sessions/month',
      'Nutrition consultation',
      'Sauna & steam room access',
      'Guest passes (2/month)',
    ],
    status: 'active',
    maxMembers: null,
    createdDate: '2024-01-01',
    lastModified: '2024-01-15',
  },
  {
    id: 'PKG003',
    name: 'VIP Annual',
    type: 'vip',
    duration: 'annual',
    price: 1199.99,
    description: 'Premium annual membership with exclusive benefits',
    features: [
      'All Premium features',
      'Unlimited personal training',
      'Priority booking',
      'Exclusive VIP lounge access',
      'Massage therapy sessions',
      'Unlimited guest passes',
      'Free merchandise',
      'Nutrition meal planning',
    ],
    status: 'active',
    maxMembers: 100,
    createdDate: '2024-01-01',
    lastModified: '2024-02-01',
  },
  {
    id: 'PKG004',
    name: 'Student Discount',
    type: 'student',
    duration: 'monthly',
    price: 29.99,
    description: 'Special pricing for students with valid ID',
    features: [
      'Gym equipment access',
      'Locker room access',
      'Group fitness classes',
      'Study areas',
    ],
    status: 'active',
    maxMembers: null,
    createdDate: '2024-01-01',
    lastModified: '2024-01-10',
  },
  {
    id: 'PKG005',
    name: 'Corporate Package',
    type: 'corporate',
    duration: 'annual',
    price: 899.99,
    description: 'Corporate membership for employees',
    features: [
      'All Premium features',
      'Corporate wellness programs',
      'Team building activities',
      'Health screenings',
      'Flexible scheduling',
    ],
    status: 'active',
    maxMembers: null,
    createdDate: '2024-01-01',
    lastModified: '2024-01-20',
  },
  {
    id: 'PKG006',
    name: 'Family Package',
    type: 'family',
    duration: 'annual',
    price: 1499.99,
    description: 'Family membership for up to 4 members',
    features: [
      'All Premium features for family',
      'Kids programs',
      'Family fitness classes',
      'Swimming pool access',
      'Family locker rooms',
    ],
    status: 'active',
    maxMembers: 4,
    createdDate: '2024-01-01',
    lastModified: '2024-01-25',
  },
  {
    id: 'PKG007',
    name: 'Lifetime VIP',
    type: 'vip',
    duration: 'lifetime',
    price: 4999.99,
    description: 'One-time payment for lifetime access',
    features: [
      'All VIP features',
      'Lifetime guarantee',
      'Legacy member benefits',
      'Transferable membership',
      'Annual review and updates',
    ],
    status: 'active',
    maxMembers: 50,
    createdDate: '2024-01-01',
    lastModified: '2024-02-01',
  },
];

// Mock Member Subscriptions
export const MOCK_MEMBER_SUBSCRIPTIONS = [
  {
    id: 'SUB001',
    memberId: 'MEM001',
    memberName: 'John Doe',
    packageId: 'PKG002',
    packageName: 'Premium Monthly',
    startDate: '2024-01-15',
    endDate: '2024-02-15',
    status: 'active',
    paymentStatus: 'paid',
    autoRenewal: true,
    price: 79.99,
    paymentMethod: 'Credit Card',
    lastPaymentDate: '2024-01-15',
    nextPaymentDate: '2024-02-15',
    createdDate: '2024-01-15',
  },
  {
    id: 'SUB002',
    memberId: 'MEM002',
    memberName: 'Jane Smith',
    packageId: 'PKG003',
    packageName: 'VIP Annual',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    status: 'active',
    paymentStatus: 'paid',
    autoRenewal: true,
    price: 1199.99,
    paymentMethod: 'Bank Transfer',
    lastPaymentDate: '2024-01-01',
    nextPaymentDate: '2025-01-01',
    createdDate: '2024-01-01',
  },
  {
    id: 'SUB003',
    memberId: 'MEM003',
    memberName: 'Mike Wilson',
    packageId: 'PKG001',
    packageName: 'Basic Monthly',
    startDate: '2024-01-20',
    endDate: '2024-02-20',
    status: 'expired',
    paymentStatus: 'overdue',
    autoRenewal: false,
    price: 49.99,
    paymentMethod: 'Credit Card',
    lastPaymentDate: '2024-01-20',
    nextPaymentDate: '2024-02-20',
    createdDate: '2024-01-20',
  },
  {
    id: 'SUB004',
    memberId: 'MEM004',
    memberName: 'Sarah Johnson',
    packageId: 'PKG004',
    packageName: 'Student Discount',
    startDate: '2024-02-01',
    endDate: '2024-03-01',
    status: 'active',
    paymentStatus: 'paid',
    autoRenewal: true,
    price: 29.99,
    paymentMethod: 'Debit Card',
    lastPaymentDate: '2024-02-01',
    nextPaymentDate: '2024-03-01',
    createdDate: '2024-02-01',
  },
  {
    id: 'SUB005',
    memberId: 'MEM005',
    memberName: 'David Brown',
    packageId: 'PKG006',
    packageName: 'Family Package',
    startDate: '2024-01-10',
    endDate: '2025-01-10',
    status: 'active',
    paymentStatus: 'paid',
    autoRenewal: true,
    price: 1499.99,
    paymentMethod: 'Credit Card',
    lastPaymentDate: '2024-01-10',
    nextPaymentDate: '2025-01-10',
    createdDate: '2024-01-10',
  },
  {
    id: 'SUB006',
    memberId: 'MEM006',
    memberName: 'Lisa Davis',
    packageId: 'PKG002',
    packageName: 'Premium Monthly',
    startDate: '2024-01-25',
    endDate: '2024-02-25',
    status: 'suspended',
    paymentStatus: 'failed',
    autoRenewal: true,
    price: 79.99,
    paymentMethod: 'Credit Card',
    lastPaymentDate: '2024-01-25',
    nextPaymentDate: '2024-02-25',
    createdDate: '2024-01-25',
  },
];
