// Trainer Management Constants

export const TRAINER_SPECIALIZATIONS = {
  personalTraining: 'Personal Training',
  weightLifting: 'Weight Lifting',
  cardio: 'Cardio Training',
  yoga: 'Yoga & Flexibility',
  pilates: 'Pilates',
  crossfit: 'CrossFit',
  boxing: 'Boxing & Martial Arts',
  swimming: 'Swimming',
  groupFitness: 'Group Fitness',
  rehabilitation: 'Rehabilitation',
  nutrition: 'Nutrition Coaching',
  bodybuilding: 'Bodybuilding',
};

export const TRAINER_STATUS = {
  active: 'Active',
  inactive: 'Inactive',
  onLeave: 'On Leave',
  suspended: 'Suspended',
};

export const CERTIFICATION_STATUS = {
  valid: 'Valid',
  expired: 'Expired',
  pending: 'Pending Renewal',
  na: 'Not Required',
};

export const AVAILABILITY_SLOTS = {
  morning: 'Morning (6AM - 12PM)',
  afternoon: 'Afternoon (12PM - 6PM)',
  evening: 'Evening (6PM - 10PM)',
  late: 'Late Night (10PM - 12AM)',
};

export const EXPERIENCE_LEVELS = {
  junior: '1-2 Years',
  intermediate: '3-5 Years',
  senior: '6-10 Years',
  expert: '10+ Years',
};

export const MOCK_TRAINERS = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john.smith@tritifitness.com',
    phone: '+1 (555) 123-4567',
    dateOfBirth: '1985-03-15',
    address: '123 Fitness St, Gym City, GC 12345',
    emergencyContact: {
      name: 'Jane Smith',
      phone: '+1 (555) 987-6543',
      relationship: 'Spouse',
    },
    status: 'active',
    hireDate: '2020-01-15',
    experience: 'senior',
    specializations: ['personalTraining', 'weightLifting', 'bodybuilding'],
    certifications: [
      {
        id: 'cert1',
        name: 'NASM Certified Personal Trainer',
        issuedBy: 'NASM',
        issueDate: '2019-06-01',
        expiryDate: '2025-06-01',
        status: 'valid',
      },
      {
        id: 'cert2',
        name: 'Precision Nutrition Level 1',
        issuedBy: 'Precision Nutrition',
        issueDate: '2021-03-15',
        expiryDate: '2026-03-15',
        status: 'valid',
      },
    ],
    availability: ['morning', 'afternoon'],
    hourlyRate: 75,
    maxClientsPerDay: 8,
    currentClients: 45,
    maxClients: 50,
    bio: 'Experienced personal trainer specializing in strength training and body composition. Passionate about helping clients achieve their fitness goals through personalized workout plans.',
    achievements: [
      'Trainer of the Year 2023',
      'Helped 100+ clients achieve their fitness goals',
      'Certified in advanced nutrition coaching',
    ],
    socialMedia: {
      instagram: '@johnsmith_pt',
      facebook: 'johnsmithfitness',
    },
    workSchedule: {
      monday: ['09:00-17:00'],
      tuesday: ['09:00-17:00'],
      wednesday: ['09:00-17:00'],
      thursday: ['09:00-17:00'],
      friday: ['09:00-17:00'],
      saturday: ['08:00-14:00'],
      sunday: ['rest'],
    },
    totalSessions: 1250,
    averageRating: 4.8,
    clientRetentionRate: 92,
    yearsAtGym: 4,
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@tritifitness.com',
    phone: '+1 (555) 234-5678',
    dateOfBirth: '1990-07-22',
    address: '456 Wellness Ave, Health Town, HT 67890',
    emergencyContact: {
      name: 'Mike Johnson',
      phone: '+1 (555) 876-5432',
      relationship: 'Brother',
    },
    status: 'active',
    hireDate: '2021-06-01',
    experience: 'intermediate',
    specializations: ['yoga', 'pilates', 'groupFitness'],
    certifications: [
      {
        id: 'cert3',
        name: 'RYT 500 Yoga Certification',
        issuedBy: 'Yoga Alliance',
        issueDate: '2020-01-10',
        expiryDate: '2025-01-10',
        status: 'valid',
      },
      {
        id: 'cert4',
        name: 'Pilates Method Alliance Certification',
        issuedBy: 'PMA',
        issueDate: '2021-08-15',
        expiryDate: '2024-08-15',
        status: 'expired',
      },
    ],
    availability: ['morning', 'evening'],
    hourlyRate: 65,
    maxClientsPerDay: 12,
    currentClients: 35,
    maxClients: 40,
    bio: 'Certified yoga instructor and pilates specialist with a focus on mindful movement and holistic wellness. Dedicated to creating inclusive and supportive fitness environments.',
    achievements: [
      'Led 500+ successful group fitness sessions',
      'Specialized in prenatal and postnatal fitness',
      'Community wellness advocate',
    ],
    socialMedia: {
      instagram: '@sarahflow_yoga',
      youtube: 'SarahJohnsonFitness',
    },
    workSchedule: {
      monday: ['06:00-10:00', '18:00-21:00'],
      tuesday: ['06:00-10:00', '18:00-21:00'],
      wednesday: ['06:00-10:00', '18:00-21:00'],
      thursday: ['06:00-10:00', '18:00-21:00'],
      friday: ['06:00-10:00', '18:00-21:00'],
      saturday: ['07:00-12:00'],
      sunday: ['rest'],
    },
    totalSessions: 850,
    averageRating: 4.9,
    clientRetentionRate: 88,
    yearsAtGym: 3,
  },
  {
    id: '3',
    name: 'Mike Rodriguez',
    email: 'mike.rodriguez@tritifitness.com',
    phone: '+1 (555) 345-6789',
    dateOfBirth: '1988-11-08',
    address: '789 Strong St, Power City, PC 54321',
    emergencyContact: {
      name: 'Maria Rodriguez',
      phone: '+1 (555) 765-4321',
      relationship: 'Sister',
    },
    status: 'active',
    hireDate: '2019-09-15',
    experience: 'senior',
    specializations: ['crossfit', 'boxing', 'cardio'],
    certifications: [
      {
        id: 'cert5',
        name: 'CrossFit Level 2 Trainer',
        issuedBy: 'CrossFit Inc.',
        issueDate: '2019-02-20',
        expiryDate: '2025-02-20',
        status: 'valid',
      },
      {
        id: 'cert6',
        name: 'USA Boxing Certified Coach',
        issuedBy: 'USA Boxing',
        issueDate: '2018-05-10',
        expiryDate: '2024-05-10',
        status: 'pending',
      },
    ],
    availability: ['afternoon', 'evening'],
    hourlyRate: 80,
    maxClientsPerDay: 10,
    currentClients: 38,
    maxClients: 45,
    bio: 'High-intensity training specialist with expertise in CrossFit and boxing. Focused on building functional strength and mental toughness in athletes and fitness enthusiasts.',
    achievements: [
      'Former competitive boxer',
      'CrossFit Games regional qualifier',
      'Trained 5 professional athletes',
    ],
    socialMedia: {
      instagram: '@mikepower_fitness',
      tiktok: '@mikerodriguezfit',
    },
    workSchedule: {
      monday: ['12:00-21:00'],
      tuesday: ['12:00-21:00'],
      wednesday: ['12:00-21:00'],
      thursday: ['12:00-21:00'],
      friday: ['12:00-21:00'],
      saturday: ['10:00-16:00'],
      sunday: ['rest'],
    },
    totalSessions: 1450,
    averageRating: 4.7,
    clientRetentionRate: 85,
    yearsAtGym: 5,
  },
  {
    id: '4',
    name: 'Emily Chen',
    email: 'emily.chen@tritifitness.com',
    phone: '+1 (555) 456-7890',
    dateOfBirth: '1992-04-18',
    address: '321 Zen Way, Mindful City, MC 98765',
    emergencyContact: {
      name: 'David Chen',
      phone: '+1 (555) 654-3210',
      relationship: 'Father',
    },
    status: 'active',
    hireDate: '2022-03-01',
    experience: 'intermediate',
    specializations: ['swimming', 'rehabilitation', 'nutrition'],
    certifications: [
      {
        id: 'cert7',
        name: 'Water Safety Instructor',
        issuedBy: 'American Red Cross',
        issueDate: '2021-07-01',
        expiryDate: '2024-07-01',
        status: 'valid',
      },
      {
        id: 'cert8',
        name: 'Corrective Exercise Specialist',
        issuedBy: 'NASM',
        issueDate: '2022-01-15',
        expiryDate: '2026-01-15',
        status: 'valid',
      },
    ],
    availability: ['morning', 'afternoon'],
    hourlyRate: 70,
    maxClientsPerDay: 6,
    currentClients: 25,
    maxClients: 30,
    bio: 'Aquatic fitness specialist and corrective exercise expert. Passionate about injury prevention and helping clients recover through targeted exercise and nutrition guidance.',
    achievements: [
      'Certified nutritionist',
      'Specialist in post-injury rehabilitation',
      'Published research on aquatic therapy',
    ],
    socialMedia: {
      linkedin: 'emily-chen-fitness',
      instagram: '@emily_aquafit',
    },
    workSchedule: {
      monday: ['08:00-16:00'],
      tuesday: ['08:00-16:00'],
      wednesday: ['08:00-16:00'],
      thursday: ['08:00-16:00'],
      friday: ['08:00-16:00'],
      saturday: ['rest'],
      sunday: ['rest'],
    },
    totalSessions: 420,
    averageRating: 4.9,
    clientRetentionRate: 94,
    yearsAtGym: 2,
  },
  {
    id: '5',
    name: 'Alex Thompson',
    email: 'alex.thompson@tritifitness.com',
    phone: '+1 (555) 567-8901',
    dateOfBirth: '1987-09-12',
    address: '654 Flex Blvd, Motion City, MC 13579',
    emergencyContact: {
      name: 'Sam Thompson',
      phone: '+1 (555) 543-2109',
      relationship: 'Partner',
    },
    status: 'onLeave',
    hireDate: '2020-11-01',
    experience: 'senior',
    specializations: ['groupFitness', 'cardio', 'pilates'],
    certifications: [
      {
        id: 'cert9',
        name: 'ACE Group Fitness Instructor',
        issuedBy: 'ACE',
        issueDate: '2020-05-01',
        expiryDate: '2025-05-01',
        status: 'valid',
      },
      {
        id: 'cert10',
        name: 'Zumba Fitness Instructor',
        issuedBy: 'Zumba Fitness',
        issueDate: '2019-11-01',
        expiryDate: '2024-11-01',
        status: 'valid',
      },
    ],
    availability: ['evening'],
    hourlyRate: 60,
    maxClientsPerDay: 15,
    currentClients: 0, // On leave
    maxClients: 60,
    bio: 'Energetic group fitness instructor specializing in dance-based workouts and high-energy classes. Known for creating fun and motivating workout experiences.',
    achievements: [
      'Highest class attendance rates',
      'Created signature workout programs',
      'Fitness influencer with 10K+ followers',
    ],
    socialMedia: {
      instagram: '@alex_moves_fitness',
      youtube: 'AlexThompsonFit',
      tiktok: '@alexmovesfitness',
    },
    workSchedule: {
      monday: ['rest'],
      tuesday: ['rest'],
      wednesday: ['rest'],
      thursday: ['rest'],
      friday: ['rest'],
      saturday: ['rest'],
      sunday: ['rest'],
    },
    totalSessions: 980,
    averageRating: 4.6,
    clientRetentionRate: 80,
    yearsAtGym: 4,
    leaveReason: 'Maternity/Paternity Leave',
    expectedReturnDate: '2024-06-01',
  },
];

export const TRAINER_STATS = {
  totalTrainers: MOCK_TRAINERS.length,
  activeTrainers: MOCK_TRAINERS.filter((t) => t.status === 'active').length,
  averageExperience: 3.6,
  totalSessions: MOCK_TRAINERS.reduce((sum, t) => sum + t.totalSessions, 0),
  averageRating:
    MOCK_TRAINERS.reduce((sum, t) => sum + t.averageRating, 0) /
    MOCK_TRAINERS.length,
  certificationComplianceRate: 85,
};
